// Generated by sync-approved-codex-policy.ts; do not edit the pin here.
// Source: https://github.com/dbalders/TritonAI-Harness/blob/76aecbe4a9ceadd343a8cad247ceea973bafb5d8/config/tritonai-managed-config.json
export const APPROVED_CODEX_VERSION = "0.151.0";
export const HARNESS_POLICY_VERSION = 7;
