// Generated by sync-approved-codex-policy.ts; do not edit the pin here.
// Source: https://github.com/dbalders/TritonAI-Harness/blob/be6f32879d18cdfae3a12cba295ffbb9923a118d/config/tritonai-managed-config.json
export const APPROVED_CODEX_VERSION = "0.161.0";
export const HARNESS_POLICY_VERSION = 12;
