import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";
import * as path from "node:path";

export function renderApprovedCodexPolicy(source: unknown, commit: string): string {
  const config = source as { schemaVersion?: number; policyVersion?: number; provider?: { approvedCodexVersion?: unknown } };
  const version = config?.provider?.approvedCodexVersion;
  if (config?.schemaVersion !== 2 || !Number.isSafeInteger(config.policyVersion) || config.policyVersion! < 1 ||
      typeof version !== "string" || !/^(0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)$/.test(version) ||
      !/^[a-f0-9]{40}$/.test(commit)) {
    throw new Error("Harness source must have a valid approved Codex policy and full commit identity.");
  }
  return `// Generated by sync-approved-codex-policy.ts; do not edit the pin here.
// Source: https://github.com/dbalders/TritonAI-Harness/blob/${commit}/config/tritonai-managed-config.json
export const APPROVED_CODEX_VERSION = ${JSON.stringify(version)};
export const HARNESS_POLICY_VERSION = ${config.policyVersion};
`;
}

if (require.main === module) {
  const [checkout, ref] = process.argv.slice(2);
  if (!checkout || !ref) throw new Error("Usage: sync-approved-codex-policy <Harness checkout> <commit-or-ref>");
  const commit = execFileSync("git", ["-C", checkout, "rev-parse", "--verify", `${ref}^{commit}`], { encoding: "utf8" }).trim();
  const source = execFileSync("git", ["-C", checkout, "show", `${commit}:config/tritonai-managed-config.json`], { encoding: "utf8" });
  writeFileSync(path.resolve(__dirname, "../../src/installer/approved-codex-policy.ts"), renderApprovedCodexPolicy(JSON.parse(source), commit));
}
